#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v16
# autospec commit: b858a2a
#
Name     : embree
Version  : 4.3.3
Release  : 34
URL      : https://github.com/embree/embree/archive/v4.3.3/embree-4.3.3.tar.gz
Source0  : https://github.com/embree/embree/archive/v4.3.3/embree-4.3.3.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0 MIT
Requires: embree-lib = %{version}-%{release}
Requires: embree-libexec = %{version}-%{release}
Requires: embree-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : cmake
BuildRequires : git
BuildRequires : glfw-dev
BuildRequires : glibc-dev
BuildRequires : llvm
BuildRequires : llvm-dev
BuildRequires : mesa-dev
BuildRequires : oiio-dev
BuildRequires : tbb-dev

%description
% Embree: High Performance Ray Tracing Kernels 4.3.3
% Intel Corporation
Intel® Embree Overview
======================

%package dev
Summary: dev components for the embree package.
Group: Development
Requires: embree-lib = %{version}-%{release}
Provides: embree-devel = %{version}-%{release}
Requires: embree = %{version}-%{release}

%description dev
dev components for the embree package.


%package doc
Summary: doc components for the embree package.
Group: Documentation

%description doc
doc components for the embree package.


%package lib
Summary: lib components for the embree package.
Group: Libraries
Requires: embree-libexec = %{version}-%{release}
Requires: embree-license = %{version}-%{release}

%description lib
lib components for the embree package.


%package libexec
Summary: libexec components for the embree package.
Group: Default
Requires: embree-license = %{version}-%{release}

%description libexec
libexec components for the embree package.


%package license
Summary: license components for the embree package.
Group: Default

%description license
license components for the embree package.


%prep
%setup -q -n embree-4.3.3
cd %{_builddir}/embree-4.3.3
pushd ..
cp -a embree-4.3.3 buildavx2
popd
pushd ..
cp -a embree-4.3.3 buildavx512
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1721855291
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export CC=clang
export CXX=clang++
export LD=ld.gold
CLEAR_INTERMEDIATE_CFLAGS=${CLEAR_ORIG_CFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CLEAR_INTERMEDIATE_CXXFLAGS=${CLEAR_ORIG_CXXFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fno-lto "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fno-lto "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fno-lto "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fno-lto "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake .. -DEMBREE_ISPC_SUPPORT=false \
-DTASKING_TBB=true \
-DCMAKE_INSTALL_BINDIR=libexec  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export CC=clang
export CXX=clang++
export LD=ld.gold
CLEAR_INTERMEDIATE_CFLAGS=${CLEAR_ORIG_CFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CLEAR_INTERMEDIATE_CXXFLAGS=${CLEAR_ORIG_CXXFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fno-lto "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fno-lto "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fno-lto "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fno-lto "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake .. -DEMBREE_ISPC_SUPPORT=false \
-DTASKING_TBB=true \
-DCMAKE_INSTALL_BINDIR=libexec  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd
pushd ../buildavx512/
mkdir -p clr-build-avx512
pushd clr-build-avx512
export GCC_IGNORE_WERROR=1
export CC=clang
export CXX=clang++
export LD=ld.gold
CLEAR_INTERMEDIATE_CFLAGS=${CLEAR_ORIG_CFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CLEAR_INTERMEDIATE_CXXFLAGS=${CLEAR_ORIG_CXXFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fno-lto "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fno-lto "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fno-lto "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fno-lto "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v4
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v4 -mprefer-vector-width=512 -Wl,-z,x86-64-v4 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v4 -mprefer-vector-width=512 "
%cmake .. -DEMBREE_ISPC_SUPPORT=false \
-DTASKING_TBB=true \
-DCMAKE_INSTALL_BINDIR=libexec  -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
pushd clr-build; ctest %{?_smp_mflags} -E verify; popd

%install
export GCC_IGNORE_WERROR=1
export CC=clang
export CXX=clang++
export LD=ld.gold
CLEAR_INTERMEDIATE_CFLAGS=${CLEAR_ORIG_CFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CLEAR_INTERMEDIATE_CXXFLAGS=${CLEAR_ORIG_CXXFLAGS/ -Wa,/ -fno-integrated-as -Wa,}
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -fno-lto "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fno-lto "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -fno-lto "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -fno-lto "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1721855291
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/embree
cp %{_builddir}/embree-%{version}/LICENSE.txt %{buildroot}/usr/share/package-licenses/embree/2b8b815229aa8a61e483fb4ba0588b8b6c491890 || :
cp %{_builddir}/embree-%{version}/tutorials/common/imgui/LICENSE.txt %{buildroot}/usr/share/package-licenses/embree/0fb5bee742924bb47ce9a75ca1a91dc37f962152 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
pushd ../buildavx512/
GOAMD64=v4
pushd clr-build-avx512
%make_install_v4  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
## install_append content
rm -fr %{buildroot}*/usr/src/
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}
/usr/bin/elf-move.py avx512 %{buildroot}-v4 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/embree-vars.csh
/usr/embree-vars.sh

%files dev
%defattr(-,root,root,-)
/usr/include/embree4/rtcore.h
/usr/include/embree4/rtcore.isph
/usr/include/embree4/rtcore_buffer.h
/usr/include/embree4/rtcore_buffer.isph
/usr/include/embree4/rtcore_builder.h
/usr/include/embree4/rtcore_common.h
/usr/include/embree4/rtcore_common.isph
/usr/include/embree4/rtcore_config.h
/usr/include/embree4/rtcore_device.h
/usr/include/embree4/rtcore_device.isph
/usr/include/embree4/rtcore_geometry.h
/usr/include/embree4/rtcore_geometry.isph
/usr/include/embree4/rtcore_quaternion.h
/usr/include/embree4/rtcore_quaternion.isph
/usr/include/embree4/rtcore_ray.h
/usr/include/embree4/rtcore_ray.isph
/usr/include/embree4/rtcore_scene.h
/usr/include/embree4/rtcore_scene.isph
/usr/lib64/cmake/embree-4.3.3/embree-config-version.cmake
/usr/lib64/cmake/embree-4.3.3/embree-config.cmake
/usr/lib64/cmake/embree-4.3.3/embree-targets-relwithdebinfo.cmake
/usr/lib64/cmake/embree-4.3.3/embree-targets.cmake
/usr/lib64/libembree4.so
/usr/share/man/man3/RTCBufferType.4embree4
/usr/share/man/man3/RTCCurveFlags.4embree4
/usr/share/man/man3/RTCFeatureFlags.4embree4
/usr/share/man/man3/RTCFormat.4embree4
/usr/share/man/man3/RTCHit.4embree4
/usr/share/man/man3/RTCHitN.4embree4
/usr/share/man/man3/RTCQuaternionDecomposition.4embree4
/usr/share/man/man3/RTCRay.4embree4
/usr/share/man/man3/RTCRayHit.4embree4
/usr/share/man/man3/RTCRayHitN.4embree4
/usr/share/man/man3/RTCRayN.4embree4
/usr/share/man/man3/RTC_GEOMETRY_TYPE_CURVE.4embree4
/usr/share/man/man3/RTC_GEOMETRY_TYPE_GRID.4embree4
/usr/share/man/man3/RTC_GEOMETRY_TYPE_INSTANCE.4embree4
/usr/share/man/man3/RTC_GEOMETRY_TYPE_INSTANCE_ARRAY.4embree4
/usr/share/man/man3/RTC_GEOMETRY_TYPE_POINT.4embree4
/usr/share/man/man3/RTC_GEOMETRY_TYPE_QUAD.4embree4
/usr/share/man/man3/RTC_GEOMETRY_TYPE_SUBDIVISION.4embree4
/usr/share/man/man3/RTC_GEOMETRY_TYPE_TRIANGLE.4embree4
/usr/share/man/man3/RTC_GEOMETRY_TYPE_USER.4embree4
/usr/share/man/man3/rtcAttachGeometry.4embree4
/usr/share/man/man3/rtcAttachGeometryByID.4embree4
/usr/share/man/man3/rtcBuildBVH.4embree4
/usr/share/man/man3/rtcCollide.4embree4
/usr/share/man/man3/rtcCommitGeometry.4embree4
/usr/share/man/man3/rtcCommitScene.4embree4
/usr/share/man/man3/rtcDetachGeometry.4embree4
/usr/share/man/man3/rtcDisableGeometry.4embree4
/usr/share/man/man3/rtcEnableGeometry.4embree4
/usr/share/man/man3/rtcFilterIntersection.4embree4
/usr/share/man/man3/rtcFilterOcclusion.4embree4
/usr/share/man/man3/rtcForwardIntersect1.4embree4
/usr/share/man/man3/rtcForwardIntersect4.4embree4
/usr/share/man/man3/rtcForwardOccluded1.4embree4
/usr/share/man/man3/rtcForwardOccluded4.4embree4
/usr/share/man/man3/rtcGetBufferData.4embree4
/usr/share/man/man3/rtcGetDeviceError.4embree4
/usr/share/man/man3/rtcGetDeviceLastErrorMessage.4embree4
/usr/share/man/man3/rtcGetDeviceProperty.4embree4
/usr/share/man/man3/rtcGetErrorString.4embree4
/usr/share/man/man3/rtcGetGeometry.4embree4
/usr/share/man/man3/rtcGetGeometryBufferData.4embree4
/usr/share/man/man3/rtcGetGeometryFace.4embree4
/usr/share/man/man3/rtcGetGeometryFirstHalfEdge.4embree4
/usr/share/man/man3/rtcGetGeometryNextHalfEdge.4embree4
/usr/share/man/man3/rtcGetGeometryOppositeHalfEdge.4embree4
/usr/share/man/man3/rtcGetGeometryPreviousHalfEdge.4embree4
/usr/share/man/man3/rtcGetGeometryThreadSafe.4embree4
/usr/share/man/man3/rtcGetGeometryTransform.4embree4
/usr/share/man/man3/rtcGetGeometryTransformEx.4embree4
/usr/share/man/man3/rtcGetGeometryTransformFromScene.4embree4
/usr/share/man/man3/rtcGetGeometryUserData.4embree4
/usr/share/man/man3/rtcGetGeometryUserDataFromScene.4embree4
/usr/share/man/man3/rtcGetSYCLDeviceFunctionPointer.4embree4
/usr/share/man/man3/rtcGetSceneBounds.4embree4
/usr/share/man/man3/rtcGetSceneDevice.4embree4
/usr/share/man/man3/rtcGetSceneFlags.4embree4
/usr/share/man/man3/rtcGetSceneLinearBounds.4embree4
/usr/share/man/man3/rtcInitIntersectArguments.4embree4
/usr/share/man/man3/rtcInitOccludedArguments.4embree4
/usr/share/man/man3/rtcInitPointQueryContext.4embree4
/usr/share/man/man3/rtcInitQuaternionDecomposition.4embree4
/usr/share/man/man3/rtcInitRayQueryContext.4embree4
/usr/share/man/man3/rtcInterpolate.4embree4
/usr/share/man/man3/rtcInterpolateN.4embree4
/usr/share/man/man3/rtcIntersect1.4embree4
/usr/share/man/man3/rtcIntersect4.4embree4
/usr/share/man/man3/rtcInvokeIntersectFilterFromGeometry.4embree4
/usr/share/man/man3/rtcInvokeOccludedFilterFromGeometry.4embree4
/usr/share/man/man3/rtcIsSYCLDeviceSupported.4embree4
/usr/share/man/man3/rtcJoinCommitScene.4embree4
/usr/share/man/man3/rtcNewBVH.4embree4
/usr/share/man/man3/rtcNewBuffer.4embree4
/usr/share/man/man3/rtcNewDevice.4embree4
/usr/share/man/man3/rtcNewGeometry.4embree4
/usr/share/man/man3/rtcNewSYCLDevice.4embree4
/usr/share/man/man3/rtcNewScene.4embree4
/usr/share/man/man3/rtcNewSharedBuffer.4embree4
/usr/share/man/man3/rtcOccluded1.4embree4
/usr/share/man/man3/rtcOccluded4.4embree4
/usr/share/man/man3/rtcPointQuery.4embree4
/usr/share/man/man3/rtcPointQuery4.4embree4
/usr/share/man/man3/rtcReleaseBVH.4embree4
/usr/share/man/man3/rtcReleaseBuffer.4embree4
/usr/share/man/man3/rtcReleaseDevice.4embree4
/usr/share/man/man3/rtcReleaseGeometry.4embree4
/usr/share/man/man3/rtcReleaseScene.4embree4
/usr/share/man/man3/rtcRetainBVH.4embree4
/usr/share/man/man3/rtcRetainBuffer.4embree4
/usr/share/man/man3/rtcRetainDevice.4embree4
/usr/share/man/man3/rtcRetainGeometry.4embree4
/usr/share/man/man3/rtcRetainScene.4embree4
/usr/share/man/man3/rtcSYCLDeviceSelector.4embree4
/usr/share/man/man3/rtcSetDeviceErrorFunction.4embree4
/usr/share/man/man3/rtcSetDeviceMemoryMonitorFunction.4embree4
/usr/share/man/man3/rtcSetDeviceSYCLDevice.4embree4
/usr/share/man/man3/rtcSetGeometryBoundsFunction.4embree4
/usr/share/man/man3/rtcSetGeometryBuffer.4embree4
/usr/share/man/man3/rtcSetGeometryBuildQuality.4embree4
/usr/share/man/man3/rtcSetGeometryDisplacementFunction.4embree4
/usr/share/man/man3/rtcSetGeometryEnableFilterFunctionFromArguments.4embree4
/usr/share/man/man3/rtcSetGeometryInstancedScene.4embree4
/usr/share/man/man3/rtcSetGeometryInstancedScenes.4embree4
/usr/share/man/man3/rtcSetGeometryIntersectFilterFunction.4embree4
/usr/share/man/man3/rtcSetGeometryIntersectFunction.4embree4
/usr/share/man/man3/rtcSetGeometryMask.4embree4
/usr/share/man/man3/rtcSetGeometryMaxRadiusScale.4embree4
/usr/share/man/man3/rtcSetGeometryOccludedFilterFunction.4embree4
/usr/share/man/man3/rtcSetGeometryOccludedFunction.4embree4
/usr/share/man/man3/rtcSetGeometryPointQueryFunction.4embree4
/usr/share/man/man3/rtcSetGeometrySubdivisionMode.4embree4
/usr/share/man/man3/rtcSetGeometryTessellationRate.4embree4
/usr/share/man/man3/rtcSetGeometryTimeRange.4embree4
/usr/share/man/man3/rtcSetGeometryTimeStepCount.4embree4
/usr/share/man/man3/rtcSetGeometryTopologyCount.4embree4
/usr/share/man/man3/rtcSetGeometryTransform.4embree4
/usr/share/man/man3/rtcSetGeometryTransformQuaternion.4embree4
/usr/share/man/man3/rtcSetGeometryUserData.4embree4
/usr/share/man/man3/rtcSetGeometryUserPrimitiveCount.4embree4
/usr/share/man/man3/rtcSetGeometryVertexAttributeCount.4embree4
/usr/share/man/man3/rtcSetGeometryVertexAttributeTopology.4embree4
/usr/share/man/man3/rtcSetNewGeometryBuffer.4embree4
/usr/share/man/man3/rtcSetSceneBuildQuality.4embree4
/usr/share/man/man3/rtcSetSceneFlags.4embree4
/usr/share/man/man3/rtcSetSceneProgressMonitorFunction.4embree4
/usr/share/man/man3/rtcSetSharedGeometryBuffer.4embree4
/usr/share/man/man3/rtcUpdateGeometryBuffer.4embree4

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/embree4/CHANGELOG.md
/usr/share/doc/embree4/LICENSE.txt
/usr/share/doc/embree4/README.md
/usr/share/doc/embree4/readme.pdf
/usr/share/doc/embree4/third-party-programs-DPCPP.txt
/usr/share/doc/embree4/third-party-programs-OIDN.txt
/usr/share/doc/embree4/third-party-programs-TBB.txt
/usr/share/doc/embree4/third-party-programs-oneAPI-DPCPP.txt
/usr/share/doc/embree4/third-party-programs.txt

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libembree4.so.4
/V4/usr/lib64/libembree4.so.4
/usr/lib64/libembree4.so.4

%files libexec
%defattr(-,root,root,-)
/V3/usr/libexec/embree_buildbench
/V3/usr/libexec/embree_bvh_access
/V3/usr/libexec/embree_bvh_builder
/V3/usr/libexec/embree_closest_point
/V3/usr/libexec/embree_collide
/V3/usr/libexec/embree_convert
/V3/usr/libexec/embree_curve_geometry
/V3/usr/libexec/embree_displacement_geometry
/V3/usr/libexec/embree_dynamic_scene
/V3/usr/libexec/embree_forest
/V3/usr/libexec/embree_grid_geometry
/V3/usr/libexec/embree_hair_geometry
/V3/usr/libexec/embree_info
/V3/usr/libexec/embree_instanced_geometry
/V3/usr/libexec/embree_interpolation
/V3/usr/libexec/embree_intersection_filter
/V3/usr/libexec/embree_lazy_geometry
/V3/usr/libexec/embree_minimal
/V3/usr/libexec/embree_motion_blur_geometry
/V3/usr/libexec/embree_multiscene_geometry
/V3/usr/libexec/embree_next_hit
/V3/usr/libexec/embree_pathtracer
/V3/usr/libexec/embree_point_geometry
/V3/usr/libexec/embree_quaternion_motion_blur
/V3/usr/libexec/embree_ray_mask
/V3/usr/libexec/embree_subdivision_geometry
/V3/usr/libexec/embree_tests
/V3/usr/libexec/embree_triangle_geometry
/V3/usr/libexec/embree_user_geometry
/V3/usr/libexec/embree_verify
/V3/usr/libexec/embree_viewer
/V3/usr/libexec/embree_voronoi
/V4/usr/libexec/embree_buildbench
/V4/usr/libexec/embree_bvh_access
/V4/usr/libexec/embree_bvh_builder
/V4/usr/libexec/embree_closest_point
/V4/usr/libexec/embree_collide
/V4/usr/libexec/embree_convert
/V4/usr/libexec/embree_curve_geometry
/V4/usr/libexec/embree_displacement_geometry
/V4/usr/libexec/embree_dynamic_scene
/V4/usr/libexec/embree_forest
/V4/usr/libexec/embree_grid_geometry
/V4/usr/libexec/embree_hair_geometry
/V4/usr/libexec/embree_info
/V4/usr/libexec/embree_instanced_geometry
/V4/usr/libexec/embree_interpolation
/V4/usr/libexec/embree_intersection_filter
/V4/usr/libexec/embree_lazy_geometry
/V4/usr/libexec/embree_minimal
/V4/usr/libexec/embree_motion_blur_geometry
/V4/usr/libexec/embree_multiscene_geometry
/V4/usr/libexec/embree_next_hit
/V4/usr/libexec/embree_pathtracer
/V4/usr/libexec/embree_point_geometry
/V4/usr/libexec/embree_quaternion_motion_blur
/V4/usr/libexec/embree_ray_mask
/V4/usr/libexec/embree_subdivision_geometry
/V4/usr/libexec/embree_tests
/V4/usr/libexec/embree_triangle_geometry
/V4/usr/libexec/embree_user_geometry
/V4/usr/libexec/embree_verify
/V4/usr/libexec/embree_viewer
/V4/usr/libexec/embree_voronoi
/usr/libexec/embree_buildbench
/usr/libexec/embree_bvh_access
/usr/libexec/embree_bvh_builder
/usr/libexec/embree_closest_point
/usr/libexec/embree_collide
/usr/libexec/embree_convert
/usr/libexec/embree_curve_geometry
/usr/libexec/embree_displacement_geometry
/usr/libexec/embree_dynamic_scene
/usr/libexec/embree_forest
/usr/libexec/embree_grid_geometry
/usr/libexec/embree_hair_geometry
/usr/libexec/embree_info
/usr/libexec/embree_instanced_geometry
/usr/libexec/embree_interpolation
/usr/libexec/embree_intersection_filter
/usr/libexec/embree_lazy_geometry
/usr/libexec/embree_minimal
/usr/libexec/embree_motion_blur_geometry
/usr/libexec/embree_multiscene_geometry
/usr/libexec/embree_next_hit
/usr/libexec/embree_pathtracer
/usr/libexec/embree_point_geometry
/usr/libexec/embree_quaternion_motion_blur
/usr/libexec/embree_ray_mask
/usr/libexec/embree_subdivision_geometry
/usr/libexec/embree_tests
/usr/libexec/embree_triangle_geometry
/usr/libexec/embree_user_geometry
/usr/libexec/embree_verify
/usr/libexec/embree_viewer
/usr/libexec/embree_voronoi
/usr/libexec/models/build.bench
/usr/libexec/models/cone_0.ecs
/usr/libexec/models/cone_0.xml
/usr/libexec/models/cornell_box.ecs
/usr/libexec/models/cornell_box.mtl
/usr/libexec/models/cornell_box.obj
/usr/libexec/models/cornell_box.xml
/usr/libexec/models/cornell_box.xml.bin
/usr/libexec/models/cornell_box_instanced.ecs
/usr/libexec/models/cornell_box_instanced.xml
/usr/libexec/models/cornell_box_mblur.xml
/usr/libexec/models/cornell_box_mblur.xml.bin
/usr/libexec/models/curve0.xml
/usr/libexec/models/curve1.xml
/usr/libexec/models/curve_flat.ecs
/usr/libexec/models/curve_flat.xml
/usr/libexec/models/curve_geometry.xml
/usr/libexec/models/curve_oriented.ecs
/usr/libexec/models/curve_oriented.xml
/usr/libexec/models/curve_round.ecs
/usr/libexec/models/curve_round.xml
/usr/libexec/models/cylinder.ecs
/usr/libexec/models/cylinder.xml
/usr/libexec/models/furBall_A.bin
/usr/libexec/models/furBall_A.ecs
/usr/libexec/models/furBall_A.xml
/usr/libexec/models/grid4x4.ecs
/usr/libexec/models/grid4x4.xml
/usr/libexec/models/grid4x4_mb.ecs
/usr/libexec/models/grid4x4_mb.xml
/usr/libexec/models/hair0.ecs
/usr/libexec/models/hair0.xml
/usr/libexec/models/hair1.ecs
/usr/libexec/models/hair1.xml
/usr/libexec/models/linesegments.ecs
/usr/libexec/models/linesegments.xml
/usr/libexec/models/mblur_time_range_curve.xml
/usr/libexec/models/mblur_time_range_grid.xml
/usr/libexec/models/mblur_time_range_line.xml
/usr/libexec/models/mblur_time_range_quad.xml
/usr/libexec/models/mblur_time_range_triangle.xml
/usr/libexec/models/meta_bvh.ecs
/usr/libexec/models/meta_bvh.xml
/usr/libexec/models/meta_bvh_mb.ecs
/usr/libexec/models/meta_bvh_mb.xml
/usr/libexec/models/oriented_bspline_curve_twisted.xml
/usr/libexec/models/oriented_curve0.xml
/usr/libexec/models/oriented_curve1.xml
/usr/libexec/models/oriented_curve_large_curvature.ecs
/usr/libexec/models/oriented_curve_large_curvature.xml
/usr/libexec/models/oriented_curves.xml
/usr/libexec/models/oriented_curves_sycl.ecs
/usr/libexec/models/oriented_curves_sycl.xml
/usr/libexec/models/oriented_hermite_curve_twisted.xml
/usr/libexec/models/points.ecs
/usr/libexec/models/points.xml
/usr/libexec/models/points_mb.ecs
/usr/libexec/models/points_mb.xml
/usr/libexec/models/quad_mb.ecs
/usr/libexec/models/quad_mb.xml
/usr/libexec/models/round_curves_sycl.ecs
/usr/libexec/models/round_curves_sycl.xml
/usr/libexec/models/round_line_segments_0.ecs
/usr/libexec/models/round_line_segments_0.xml
/usr/libexec/models/round_line_segments_1.ecs
/usr/libexec/models/round_line_segments_1.xml
/usr/libexec/models/round_line_segments_2.ecs
/usr/libexec/models/round_line_segments_2.xml
/usr/libexec/models/round_line_segments_3.ecs
/usr/libexec/models/round_line_segments_3.xml
/usr/libexec/models/round_line_segments_4.ecs
/usr/libexec/models/round_line_segments_4.xml
/usr/libexec/models/round_line_segments_5.ecs
/usr/libexec/models/round_line_segments_5.xml
/usr/libexec/models/round_line_segments_6.ecs
/usr/libexec/models/round_line_segments_6.xml
/usr/libexec/models/sphere_instancing_mb.ecs
/usr/libexec/models/sphere_instancing_mb.xml
/usr/libexec/models/spheres.ecs
/usr/libexec/models/spheres.mtl
/usr/libexec/models/spheres.obj
/usr/libexec/models/subdiv0.ecs
/usr/libexec/models/subdiv0.xml
/usr/libexec/models/subdiv1.ecs
/usr/libexec/models/subdiv1.xml
/usr/libexec/models/subdiv3.ecs
/usr/libexec/models/subdiv3.xml
/usr/libexec/models/subdiv4.ecs
/usr/libexec/models/subdiv4.xml
/usr/libexec/models/subdiv5.ecs
/usr/libexec/models/subdiv5.xml
/usr/libexec/models/subdiv6.ecs
/usr/libexec/models/subdiv6.xml
/usr/libexec/models/subdiv7.ecs
/usr/libexec/models/subdiv7.xml
/usr/libexec/models/subdiv8.ecs
/usr/libexec/models/subdiv8.xml
/usr/libexec/models/subdiv9.ecs
/usr/libexec/models/subdiv9.xml
/usr/libexec/models/subdiv_no_boundary.ecs
/usr/libexec/models/subdiv_no_boundary.xml
/usr/libexec/models/subdiv_pin_all.ecs
/usr/libexec/models/subdiv_pin_all.xml
/usr/libexec/models/subdiv_pin_boundary.ecs
/usr/libexec/models/subdiv_pin_boundary.xml
/usr/libexec/models/subdiv_pin_corners.ecs
/usr/libexec/models/subdiv_pin_corners.xml
/usr/libexec/models/subdiv_smooth_boundary.ecs
/usr/libexec/models/subdiv_smooth_boundary.xml
/usr/libexec/models/trace.bench
/usr/libexec/models/triangle.ecs
/usr/libexec/models/triangle.xml
/usr/libexec/models/triangle_instancing_mb.ecs
/usr/libexec/models/triangle_instancing_mb.xml
/usr/libexec/models/triangle_instancing_qmb.ecs
/usr/libexec/models/triangle_instancing_qmb.xml
/usr/libexec/models/triangle_mb.ecs
/usr/libexec/models/triangle_mb.xml

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/embree/0fb5bee742924bb47ce9a75ca1a91dc37f962152
/usr/share/package-licenses/embree/2b8b815229aa8a61e483fb4ba0588b8b6c491890
